FROM python:3.9-slim

WORKDIR /app

# Install system dependencies for FAISS and other libraries if needed
RUN apt-get update && apt-get install -y libomp-dev && rm -rf /var/lib/apt/lists/*

COPY Requirements.txt .

RUN pip install --no-cache-dir -r Requirements.txt

COPY . .

EXPOSE 8000

# We need to run uvicorn on 0.0.0.0 directly from the root of the project
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
